### ISSUE TITLE
Related Work Missing

### ISSUE THREAD

**Issue by eyuchang** [ljcleo/Debatrix#1]
Please be advised that the LLM debate and evaluation framework were previously published.  Please discuss and compare your work with prior art to ensure thoroughness of this paper.

SocraSynth.com lists several related work including CRIT for evaluating reasonableness.

Thanks!

**Comment by ljcleo** [comment]
We thank you for sharing your research about debate evaluation, which is especially beneficial for single speech evaluation. We will include your work in the related work section of our next revision planning to be published very soon.
